version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: "bridge_db"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./volumes/data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --bind_ip=mongodb --logpath=/dev/null
  bridge_api:
    build:
      context: ./sbtc-bridge-api
    image: mijoco/bridge_api
    container_name: "bridge_api"
    environment:
      - TARGET_ENV=${TARGET_ENV}
      - btcRpcUser=${BTC_RPC_USER}
      - btcRpcPwd=${BTC_RPC_PWD}
      - btcNode=${BTC_NODE}
    ports:
      - "3010:3010"
    links:
      - mongodb
