version: "3.9"

services:
  sbtc-bridge-api:
    build:
      context: ./sbtc-bridge-api
    image: us-central1-docker.pkg.dev/core-eng/core-eng-repo/sbtc-bridge-api:latest
    container_name: "sbtc-bridge-api"
    environment:
      - PORT=80
    ports:
      - "80:80"
    labels:
      kompose.service.type: nodeport
